log_name: new_Experiment
log_dir: /home/zzefduran/Documents/exp_csvs
vis_dof: motor
trajectory:
  frequency: 30
  shape: wave
  # positive_triangle # positive_right_trapezoid # sine # trapezoid
  plot:
    show: true
    save: true

# piecewise:
#   objective: vel # pos # torque
#   values:
#   - [0.0, 0.0]
#   - [1/30, 0.0]
#   - [2/30, 2.0]
#   - [10-2/30, 2.0]
#   - [10-1/30, 0.0]
#   - [10.0, 0.0]


wave:
  frequency:
    start: 0.3
    stop: 1.0
    step: 0.1
  separator: 2 #[sec]
  amplitude_factor:
    start: 1.0
    stop: 1.0
    step: 0.2
  partial:
    enable: true
    total_parts: 2
    part: 1
  repeat: 1 #2
  trapezoid:
    bounds_ratio: 0.3
  stomping:
    amplitude: 0.1 # hip angle [rad]

dof_pos_traj_limit:
  motor: 1515354

