## exp configuration ##

# motor #
exp_type: 'KTAU'
motor_name: 52 #maxon EC-i 52
ktau: 0.0910 #maxon EC-i 52
gear_ratio: 1.00 #maxon EC-i 52

current_bias: False
bias: -0.032
 
## trajectory parameters #
# trajectory_type: 'traj_all_ramp' #ramping all the way from torques_start to torques_end
# trajectory_type: 'ramp'   #ramping for each torque from the previous one
trajectory_type: 'ramp_for_each_torq' #ramping up from and back to zero for each torque 
# trajectory_type: 'circle' 
slowrampstartend: True  # start and ends with ramping slowly to the start torque value
iteration_time: 1
dt: 0.01
record_all: False

torques_range:
  torques_start: 0
  torques_end: 2
  torques_step: 0.1

load_range:
  load_start: 2.0
  load_end: 2.0
  load_step: 0.2

velocity_range:
  vel_start: 0
  vel_end: 0
  vel_step: 2


torque_amplitude: 0
velocity_amplitude: 0

itertate:
  exp_iterations: 1
  concat: True


# exp components #
korad_on: True
korad_type: 'ka30000'  #'kel103'
torque_meter_on: True
motor_on: True
supply:
  supply_control: True
  set_voltage: 48


