## exp configuration ##

# motor #
exp_type: 'DYNAMIC_KTAU'
# motor_name: 8064
# motor_name: rmd-x6-s2
# ktau: 0.0859 #8064
ktau: 0.0834 #rmd
# gear_ratio: 0.016 #8064
gear_ratio: 0.028 #rmd-x6-s2
# motor_name: 7010
# motor_name: RMD

current_bias: False
bias: -0.032

# trajectory parameters 
# trajectory_type: 'ramp'
# trajectory_type: 'ramp'
trajectory_type: 'ramp_for_each_torq'
# trajectory_type: 'circle'
rampupdown: True
slowrampstartend: True
iteration_time: 2
dt: 0.01

torques_range:
  torques_start: 10
  torques_end: 35
  torques_step: 5

velocity_range:
  vel_start: 2.0
  vel_end: 2.0
  vel_step: 1.0

load_range:
  load_start: 0.0
  load_end: 0.7
  load_step: 0.1


torque_amplitude: 0
velocity_amplitude: 0

itertate:
  exp_iterations: 1
  concat: True


# exp components #
korad_on: True
korad_type: 'ka30000'  #'kel103'
torque_meter_on: True
motor_on: True
supply:
  supply_control: True
  set_voltage: 48



