## exp configuration ##

# motor #
exp_type: 'KTAU'  # "DYNAMIC_KTAU" , "VEL_TORQUE"
motor_name: rmd-x6-s2
# motor_name: 8064
# motor_name: 7010
# motor_name: MAXON
ktau: 0.0834
# ktau: 0.0909
# ktau: 0.091
# ktau: 0.0859
# ktau: 0.0867
# ktau: 0.112 #rmd
# gear_ratio: 1
# gear_ratio: 0.100
# gear_ratio: 0.016 #8064
gear_ratio: 0.028 #rmd-x6-s2

current_bias: False
bias: -0.032


# trajectory parameters #
# trajectory_type: 'traj_all_ramp' #ramping all the way from torques_start to torques_end
# trajectory_type: 'ramp'   #ramping for each torque from the previous one
trajectory_type: 'ramp_for_each_torq' #ramping up from and back to zero for each torque 
# trajectory_type: 'circle' 
slowrampstartend: True  # start and ends with ramping slowly to the start torque value
iteration_time: 3
dt: 0.01
record_all: False

torques_range:
  torques_start: 2
  torques_end: 40
  torques_step: 2

load_range:
  load_start: 2.0
  load_end: 2.0
  load_step: 0.2

velocity_range:
  vel_start: 0
  vel_end: 0
  vel_step: 2


torque_amplitude: 0
velocity_amplitude: 0

itertate:
  exp_iterations: 1
  concat: True


# exp components #
korad_on: True
korad_type: 'ka30000'  #'kel103'
torque_meter_on: True
motor_on: True
supply:
  supply_control: True
  set_voltage: 48


